# Generated by Django 6.1.1 on 2026-10-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
