# Generated by Django 6.1.1 on 2026-10-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnerprofile_deleted_at_partnerprofile_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='notify_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='WhatsApp number in E.164 format, e.g. +919876543210.', max_length=20),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='whatsapp_opt_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
