# Generated by Django 6.1.1 on 2026-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticket_deleted_at_ticket_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Admin response visible to the partner.', null=True),
        ),
    ]
