# Generated by Django 6.1.1 on 2026-10-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnerprofile_deleted_at_partnerprofile_deleted_by_and_more'),
        ('portal_content', '0002_announcement_deleted_at_announcement_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to show to ALL partners. Select specific partners to make it private.', related_name='announcements', to='partners.partnerprofile'),
        ),
        migrations.AddField(
            model_name='document',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to show to ALL partners. Select specific partners to make it private.', related_name='documents', to='partners.partnerprofile'),
        ),
    ]
