# Generated by Django 6.1.1 on 2026-10-07 08:12

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_content', '0003_announcement_visible_to_document_visible_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=core.storage.DatabaseFileStorage, upload_to='documents/'),
        ),
    ]
